# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default
  #vmImage: ubuntu-latest

steps:
- task: terraform deployed 
  displayName: 'terraform latest'

- task: terraform -tasks
  displayName: 'terraform init'
  inputs:
    backendserviceArm: 'praveenatukuri888'
    backendAzureRmResourceGroupName: 'test-rg'
    backendAzureRmStorageAccountName: 'tfbackup'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: '6c4b37cc-94e2-463b-84cb-ffd0dd27a50b'