trigger:
- master123

pool: Default
  #vmImage: 'ubuntu-latest'
  
stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - script: sudo apt install unzip
        displayName: 'unzip downloading' 
      - task: TerraformInstaller@0
        inputs:
         terraformVersion: 'latest'

      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1 (6c4b37cc-94e2-463b-84cb-ffd0dd27a50b)'
          backendAzureRmResourceGroupName: 'test-rg'
          backendAzureRmStorageAccountName: 'tfbackup'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'Azure subscription 1 (6c4b37cc-94e2-463b-84cb-ffd0dd27a50b)'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'Azure subscription 1 (6c4b37cc-94e2-463b-84cb-ffd0dd27a50b)'