trigger:
- master123

pool: Default
  #vmImage: 'ubuntu-latest'
stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
  steps:

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
- stage: build
  jobs:
  - job: terraformbuild 
  - task: TerraformTaskV3@3
    displayName: 'terraform init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendAzureRmResourceGroupName: 'test-rg'
      backendAzureRmStorageAccountName: 'tf-backup'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform-tfstate'

#- stage: deploy