trigger:

- master123

pool: Default
  #vmImage: 'ubuntu-latest'
  
stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      -  script: wget  https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip /myagent
         displayName: 'instaling'
      #- script: cd myagent && mv terraform_1.2.5_linux_amd64.zip 
       # displayName: extarcting