trigger:

- master123

pool: Default
  #vmImage: 'ubuntu-latest'
  
stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        inputs:
         terraformVersion: 'latest'