trigger:

- master123

pool: Default
  #vmImage: 'ubuntu-latest'
  
stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - script: sudo apt install unzip
        displayName: 'unzip downloading' 
      - task: TerraformInstaller@0
        inputs:
         terraformVersion: 'latest'

  - stage: path     
    jobs:
    - job: path
      steps:
      - script: ls -al && chmod 700 terraform
        displayName: 'permission'