trigger:
- master123

pool: Default
  #vmImage: 'ubuntu-latest'

stages:
- stage: validate
  jobs:
  - job: validate
   # ContinueOnError: flase 
    steps:
    - task: TerraformInstaller@0
      displayName: 'terrafominstalling'
      inputs:
        terraformVersion: 'latest' 
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '**/*.zip'
        destinationFolder: 'terraform'
        cleanDestinationFolder: true
        overwriteExistingFiles: false
        pathToSevenZipTool: '/usr/local/bin/terraform'