trigger:
- master123

pool: Default
  #vmImage: 'ubuntu-latest'

stages:
- stage: validate
  jobs:
  - job: validate
   # ContinueOnError: flase 
    steps:
    - task: TerraformInstaller@0
      displayName: 'terrafominstalling'
      inputs:
        terraformVersion: 'latest' 