trigger:
- test

pool: Linuxagent
  #vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
    - job: Build
      continueOnError: false
      steps:
      - script: sudo apt install unzip
        displayName: 'unzip downloading' 

      - task: TerraformInstaller@0
        dispalyName: 'installing terraform'
        inputs:
          terraformVersion: 'latest'