trigger:
- master

pool: Default

stages:
- stage: validate
  jobs:
  - job: validate
    ContinueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'terrafominstalling'
      inputs:
        terraformVersion: 'latest'
  
    - task: TerraformTaskV3@3
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'

#- stage: deploy