# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master123

pool: Default
  #vmImage: ubuntu-latest

steps:
-  script: echo testing-pipeline
   displayName: 'pipeline-Testing'
   
-  script: echo $(Build.BuildId)
   displayName: 'Display the Build.ID'
   
-  script: ls -al && pwd
   displayName: 'list files on working directory'
stages:
- stage: validate
  jobs:
  - job: validate
  continueOnError: false
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'

#- stage: deploy