variable "azurerm_resource_group_name" {}
variable "azurerm_resource_group_location" {}
variable "azurerm_app_service_plan_name" {}
variable "environment" {}
variable "size" {}
variable "azurerm_app_service_name" {}
variable "app_service_plan_tier" {}
variable "app_service_plan_size" {}
variable "app_service_plan_size_kind" {} 