
trigger:
- test12
variables:
- group: azure-credentials

stages:
  - stage: Deploy
    jobs:
    - job: Deploy
      pool: 
       vmImage: ubuntu-latest
      steps:
      - script: sudo apt install unzip
        displayName: 'installing unzip'

      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.2.5'

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'specific'
          project: '54e39bc9-4c20-4580-b949-6639e7ff537c'
          pipeline: '21'
          buildVersionToDownload: 'latest'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformTaskV3@3
        displayName: 'terraform init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/terraform'
          backendServiceArm: '$(subscriptionid)'
          backendAzureRmResourceGroupName: 'test-rg'
          backendAzureRmStorageAccountName: 'tfbackup'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '$(KeyName)'
      - task: TerraformTaskV3@3
        displayName: 'terraform apply'
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/terraform'
          commandOptions: '"plan.out"'
          environmentServiceNameAzureRM: '$(subscriptionid)'