trigger:
- test12
variables:
- group: azure-credentials

stages:
  - stage: Destroy
    jobs:
    - job: Destroy
      pool: 
       vmImage: ubuntu-latest
      steps:
      - script: sudo apt install unzip
        displayName: 'installing unzip'
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.2.5'
      
      - task: TerraformTaskV3@3
        displayName: 'terraform init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'app-service'
          backendAzureRmResourceGroupName: 'test-rg'
          backendAzureRmStorageAccountName: 'tfbackup'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '$(KeyName)'


      - task: TerraformTaskV3@3
        displayName: 'terraform plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: "-destroy-out"
          environmentServiceNameAzureRM: '$(subscriptionid)'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          workingDirectory: '$(System.ArtifactsDirectory)/drop/terraform'
          environmentServiceNameAzureRM: 'app-service'